### ISSUE TITLE
[INFO] question about firmware

### ISSUE THREAD

**Issue by DmA81** [duisenberg/AnyCubic-I3#2]
Hi, sorry for reaching out via in issue but I couldn't find another contact.

I would like to know if your firmware files can be used to compile an updated firmware for the Anycubic Prusa I3 [https://tinyurl.com/yadxjoen](https://tinyurl.com/yadxjoen) (not the ultrabase version) with a Trigorilla board.

Thanks !

**Comment by duisenberg** [comment]
Hi Dario, 

no problem. Sorry for the late answer, currently Im quite occupied. 

The firmware is exactly for the Anycubic Prusa I3 with Trigorilla board, as I run it. It can be compiled and
uploaded with any Arduino having the Mega hardware support installed, should work out of the box.

But – as mentioned, the configuration has some features installed/modified that may need attention. First
and most important  - my Z-driver drives both steppers.  If your current setup uses E1 either change in 
config or simply shift the plug. For me this works perfect without any changes of the driver voltage and I
have E1 free for a second extruder. 

The second is the autolevel feature. I simply have the inductive probe wired parallel to the Z endstop using
a relay. So if the probe fails the endstop catches the fall.

Further there are some settings in advanced config that might be adjusted as well, like the number of clicks 
and rotation direction for the thumb wheel.

Hope this helps, 

Greetz, 

Peter



From: Dario Mango 
Sent: Saturday, December 09, 2017 6:49 PM
To: duisenberg/AnyCubic-I3 
Cc: Subscribed 
Subject: [duisenberg/AnyCubic-I3] [INFO] question about firmware (#2)

Hi, sorry for reaching out via in issue but I couldn't find another contact.

I would like to know if your firmware files can be used to compile an updated firmware for the Anycubic Prusa I3 https://tinyurl.com/yadxjoen (not the ultrabase version) with a Trigorilla board.

Thanks !

**Comment by DmA81** [comment]
Thanks for the reply,
currently I have both the Z motors connected on the Z plugs and no inductive autolevel, so that shouldn't be a problem.
I'll close the issue and eventually open a new one if I find problems building the updated firmware.

Thanks for your work !
